In [2]:
import numpy as np

In [20]:
matrix1 = np.random.random((2,2))
matrix2 = np.array([[1,1],[1,1]])

In [21]:
print(matrix1)
print(matrix2)

[[0.25447216 0.86712696]
 [0.20232757 0.17819419]]
[[1 1]
 [1 1]]


In [22]:
print(type(matrix1))
print(type(matrix2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [23]:
print(matrix1.shape)
print(matrix2.shape)

(2, 2)
(2, 2)


In [24]:
matrix_sum = matrix1 + matrix2

In [25]:
matrix_sum

array([[1.25447216, 1.86712696],
       [1.20232757, 1.17819419]])