In [1]:
import numpy as np 

In [8]:
matrix1 = np.mat([[3,4],[5,6]])
matrix2 = np.mat([[3,4],[5,6]])
print(matrix1)
print(matrix2)

[[3 4]
 [5 6]]
[[3 4]
 [5 6]]


In [13]:
# matrix sum
matSum1 = matrix1 + matrix2
matSum2 = np.add(matrix1,matrix2)
print(matSum1)
print(matSum2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [15]:
# matrix multiplication by a scalar
matrixScalar1 = matrix1*2
matrixScalar2 = np.dot(matrix1,2)
print(matrixScalar1)
print(matrixScalar2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [18]:
# matrix product
matProduct1 = matrix1*matrix2
matProduct2 = np.multiply(matrix1,matrix2)
matProduct3 = np.matmul(matrix1,matrix2)
print(matProduct1)
print(matProduct2)
print(matProduct3)

[[29 36]
 [45 56]]
[[ 9 16]
 [25 36]]
[[29 36]
 [45 56]]


In [9]:
# matrix product with np.matmul
np.matmul(matrix1,matrix2)

matrix([[29, 36],
        [45, 56]])

In [46]:
matrix1 = np.mat([[3,4],[5,6],[7,8]])
matrix2 = np.mat([[3,4],[5,6]])
matrix3 = np.mat([[3,4],[5,6],[7,8]])
print(matrix1)
print(matrix2)
print(matrix3)
print(matrix1.shape)
print(matrix2.shape)

[[3 4]
 [5 6]
 [7 8]]
[[3 4]
 [5 6]]
[[3 4]
 [5 6]
 [7 8]]
(3, 2)
(2, 2)


In [40]:
mat1_dim = len(matrix1.shape)
for i in range(0,mat1_dim):
    print(matrix1.shape[i])

3
2


In [41]:
mat2_dim = len(matrix2.shape)
for i in range(0,mat2_dim):
    print(matrix2.shape[i])

2
2


In [42]:
# number of col in mat1 should equal number of row in mat2 by Chasles rules for matrix multiplication
def isMatrixProductAllowed(mat1,mat2):
    mat1_col_dim = mat1.shape[1]
    mat2_row_dim = mat2.shape[0]
    if (mat1_col_dim == mat2_row_dim):
        allowed = True
    else:
        allowed = False
    return allowed

In [48]:
print(isMatrixProductAllowed(matrix1,matrix2))
print(isMatrixProductAllowed(matrix1,matrix3))

True
False


In [50]:
np.matmul(matrix1,matrix2)

matrix([[29, 36],
        [45, 56],
        [61, 76]])

In [52]:
# matrix Rank: this tells the number of indepenant row or col
print(np.linalg.matrix_rank(matrix1))
print(np.linalg.matrix_rank(matrix2))
print(np.linalg.matrix_rank(matrix3))
# observation: matrix Rank can be computed for none square matrix

2
2
2


In [63]:
def isMatrixSquare(matrix):
    matrix_shape = matrix.shape
    if (matrix_shape[0]==matrix_shape[1]):
        is_squared = True
    else:
        is_squared = False
    return is_squared

In [62]:
print(isMatrixSquare(matrix1))
print(isMatrixSquare(matrix2))
print(isMatrixSquare(matrix3))

False
True
False


In [56]:
# Matrix Power
np.linalg.matrix_power(matrix2,2)
# observation: this is only allowed for squared matrix
# remark: Markov N-step Transition Matrix is squared by design - the np.linalg.matrix_power can help to compute it

matrix([[29, 36],
        [45, 56]])

In [58]:
# Identity Matrix
identity = np.identity(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
# Matrix Factorization
# https://en.wikipedia.org/wiki/Matrix_factorization_(recommender_systems)

In [67]:
# Matrix Inverse
np.linalg.inv(matrix2)
# observation: Matrix inverse can only exist for squared Matrix
# reminder: a squared Matrix is not always inversible

matrix([[-3. ,  2. ],
        [ 2.5, -1.5]])

In [71]:
# Eigen Vector and Eigen Value
la, v = np.linalg.eigvals(matrix2)
print(la)
print(v)
# observation: E

-0.21699056602830158
9.216990566028302


In [74]:
# Diagonal Matrix
diagMatrix = np.diag((1,2,3))